if [ -f "~/.zshrc.local" ]; then
	source ~/.zshrc.local
fi

[ -d /usr/local/share/npm/bin ] && PATH=/usr/local/share/npm/bin:$PATH
[ -d /usr/texbin ] && PATH=/usr/texbin:$PATH
[ -d $HOME/bin ] && PATH="$HOME/bin":$PATH

# Customize to your needs...
export PATH=$PATH

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="kphoen"
ZSH_THEME=${ZSH_THEME:-"af-magic"}

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github heroku sublime lein laravel nyan rbenv rails3 bundler django perl perlbrew vundle)

plugin_push() {
	for plugin in $argv; do
		plugins[$(($#plugins+1))]="$plugin"
	done
}

if [ $(uname) = 'Darwin' ]; then
	plugin_push osx brew gnu-utils
elif [ $(uname) = "Linux" -a -f "/etc/debian_version" ]; then
	plugin_push debian
fi

unset plugin_push

source $ZSH/oh-my-zsh.sh
